function htext = letterlabel_alignYlab(thisLetter,vpos,fontSize,hylabel)

% Set up current handles
hylabel.Units = 'normalized' ;
hylabel.Position = [hylabel.Position(1) 0.5 hylabel.Position(3)] ;

% Add label
thisLabel = ['(' thisLetter ')'] ;
htext = text(hylabel.Position(1),vpos, ...
             thisLabel, ...
             'Units','normalized', ...
             'FontSize',fontSize, ...
             'FontWeight','bold', ...
             'VerticalAlignment', 'bottom', ...
             'HorizontalAlignment', 'right') ;

end